import csv
import regex as re
import jiwer
from whisper.normalizers import BasicTextNormalizer

# CLEAN TRANSCRIPT AND GROUND TRUTH BEFORE SCORE CALCULATION


# initialize OpenAI's basic text normalizer, removes "  ", special characters, punctuation, capitalization
normalizer = BasicTextNormalizer(remove_diacritics=True)
# basic regex expression for filler words, matches duhh, uhhh, hmmm, emm, etc
basic_filler_words_regex = re.compile(
    r"(?:^|\s)[d]?[uea]*[hm]+(?=\P{L}|$)",
    flags=re.MULTILINE | re.IGNORECASE,
)
# basic regex expression for o and ohhh
other_filler_words_regex = re.compile(
    r"(?:^|\s)[o]+[h]*(?=\P{L}|$)",
    flags=re.MULTILINE | re.IGNORECASE,
)

# rule-based lexicon, matches words with similar meaning (not functional yet, can be expanded on during transcribing ground truth)
lexicon: dict[str, list[str]] = {
    'het': ["t", "'t"],
    'goede': ['goeie'],
    'goededag': ["goeiedag", "goede dag", "goeie dag"],
    'mijn': ["mn", "m'n"],
    'het is': ["tis", "ts", "t's", "'ts"],
    'oke': ["ok", 'k'],
    'er': ["d'r"],
    'snachts': ["'s nachts", "s nachts"],
    'savonds': ["s avonds", "'s avonds"],
    'sochtends': ["'s ochtends", 's ochtends'],
    'smiddags': ["'s middags", 's middags'],
    'zo een': ["zo'n"],
    'nou ja': ["nouja"],
    '': [' hè', ' hé'],
    'niet': ['nie', 'ni'],
    'elkaar': ['mekaar'],
    'etcetera': ['et cetera', 'etc'],
    'procent': ['%'],
    'euro': ['€'],
    'eigenlijk': ['eigelijk'],
    'en zo': ['enzo'],
    'wauw': ['wow', 'wouw'],
}


# Apply normalizer, basic lexicon and filler words removal
def normalize(text, level=3):
    if level > 0:
        text = text.lower()
    if level > 1:
        text = basic_filler_words_regex.sub("", text)
        text = other_filler_words_regex.sub("", text)
        text = apply_ruleset(text, lexicon)
    if level > 0:
        text = normalizer(text)
    if level > 2:
        text = remove_stutters(text)

    return text


def remove_stutters(text, sequence_length=1):

    def remove_word_punctuation(w) -> (str, bool):
        if w == '':
            return w, False
        return w[:-1] if ((w[-1] == ',') or w[-1] == '.') else w, True if w[-1] == '.' else False

    text = text.split(' ')
    stutter_index = []

    for index in range(len(text)):
        i = sequence_length
        while index + i + sequence_length - 1 < len(text):
            match = True
            for sequence_offset in range(sequence_length):
                if remove_word_punctuation(text[index + sequence_offset])[0] != remove_word_punctuation(text[index + sequence_offset + i])[0]:
                    match = False
                    break
            if not match:
                break

            for word_index in range(sequence_length):
                stutter_index.append(index + word_index + i)
            i += sequence_length

    for stutter in sorted(set(stutter_index), reverse=True):
        text.pop(stutter)

    return ' '.join(text)


def build_pattern(variant: str) -> re.Pattern:

    escaped = re.escape(variant)
    left_needs_boundary = bool(variant) and (variant[0].isalnum() or variant[0] == "'")
    right_needs_boundary = bool(variant) and (variant[-1].isalnum() or variant[-1] == "'")

    left = r"(?<![A-Za-zÀ-ÿ0-9'])" if left_needs_boundary else ""
    right = r"(?![A-Za-zÀ-ÿ0-9'])" if right_needs_boundary else ""

    return re.compile(left + escaped + right, flags=re.IGNORECASE)


def apply_ruleset(text: str, ruleset: dict[str, list[str]] = lexicon) -> str:

    pairs = []
    for target, variants in ruleset.items():
        for variant in variants:
            if variant == "":
                continue
            pairs.append((variant, target))
    pairs.sort(key=lambda p: len(p[0]), reverse=True)

    for variant, target in pairs:
        pattern = build_pattern(variant)
        text = pattern.sub(target, text)

    return text.strip()


def concat_csv_files(path1, path2):
    with open(path1, 'w', newline='', encoding='utf-8') as f_w:
        writer = csv.DictWriter(f_w)
        with open(path2, 'r', encoding='utf-8') as f_r:
            reader = csv.DictReader(f_r)
            for row in reader:
                writer.writerow(row)
            f_r.close()
            path2.unlink()
        f_w.close()


def align_sentences(gt, h):
    """
    :param gt:              str -> ground truth transcript
    :param h:               str -> hypothesis generated by an ASR model
    :return reference:      list[str] -> the ground truth split into sentences
            hypothesis:     list[str] -> the hypothesis aligned to each
                             ground truth sentence
    """

    gt = re.sub(r"[?!]+", '.', gt)
    h = re.sub(r"[?!]+", '.', h)

    aligned_text = jiwer.process_words(gt, h)

    ref_words = aligned_text.references[0]
    hyp_words = aligned_text.hypotheses[0]
    chunks = aligned_text.alignments[0]

    reference = []
    hypothesis = []
    ref_buffer = []
    hyp_buffer = []

    def flush():
        reference.append(' '.join(ref_buffer))
        hypothesis.append(' '.join(hyp_buffer))
        ref_buffer.clear()
        hyp_buffer.clear()

    for chunk in chunks:
        if chunk.type in ('equal', 'substitute'):
            for ref_idx, hyp_idx in zip(
                range(chunk.ref_start_idx, chunk.ref_end_idx),
                range(chunk.hyp_start_idx, chunk.hyp_end_idx),
            ):
                ref_word = ref_words[ref_idx]
                ref_buffer.append(ref_word)
                hyp_buffer.append(hyp_words[hyp_idx])
                if ref_word[-1] == '.':
                    flush()

        elif chunk.type == 'delete':
            for ref_idx in range(chunk.ref_start_idx, chunk.ref_end_idx):
                ref_word = ref_words[ref_idx]
                ref_buffer.append(ref_word)
                if ref_word[-1] == '.':
                    flush()

        elif chunk.type == 'insert':
            hyp_buffer.extend(hyp_words[chunk.hyp_start_idx:chunk.hyp_end_idx])

    # flush a trailing partial sentence, e.g. if gt doesn't end in '.'
    if ref_buffer or hyp_buffer:
        flush()

    return reference, hypothesis


def count_words(text):
    text = normalizer(text)
    return len(text.split(' '))


def count_sentences(text):
    text = re.sub(r"[?!]+", '.', text)
    return len(text.split('.'))


# Deletes [unaudible] sections and substitution or insertions in the hypothesis pointing to it
def remove_unaudible(gt, h):

    aligned_text = jiwer.process_words(gt, h)

    ref_words = aligned_text.references[0]
    hyp_words = aligned_text.hypotheses[0]
    chunks = aligned_text.alignments[0]

    ref_remove_idx = set()
    hyp_remove_idx = set()
    expand_left_chunks = set()   # chunk indices whose left-neighbor insert should be removed
    expand_right_chunks = set()  # chunk indices whose right-neighbor insert should be removed

    for chunk_i, chunk in enumerate(chunks):
        for idx in range(chunk.ref_start_idx, chunk.ref_end_idx):
            if "unaudible" not in ref_words[idx]:
                continue

            ref_remove_idx.add(idx)

            if chunk.type in ('substitute', 'equal'):
                offset = idx - chunk.ref_start_idx
                hyp_remove_idx.add(chunk.hyp_start_idx + offset)

            if idx == chunk.ref_start_idx:
                expand_left_chunks.add(chunk_i)
            if idx == chunk.ref_end_idx - 1:
                expand_right_chunks.add(chunk_i)

    for chunk_i in expand_left_chunks:
        if chunk_i - 1 >= 0 and chunks[chunk_i - 1].type == 'insert':
            prev = chunks[chunk_i - 1]
            hyp_remove_idx.update(range(prev.hyp_start_idx, prev.hyp_end_idx))

    for chunk_i in expand_right_chunks:
        if chunk_i + 1 < len(chunks) and chunks[chunk_i + 1].type == 'insert':
            nxt = chunks[chunk_i + 1]
            hyp_remove_idx.update(range(nxt.hyp_start_idx, nxt.hyp_end_idx))

    gt_clean = ' '.join(w for i, w in enumerate(ref_words) if i not in ref_remove_idx)
    h_clean = ' '.join(w for i, w in enumerate(hyp_words) if i not in hyp_remove_idx)

    return gt_clean, h_clean


# Clean data for category Dokter Patient directory
def dok_pat(t):
    t = t.split('\n')
    t = [line.strip for line in t]
    t = " ".join([t[i*2+1] for i in range(int(len(t)/2))])
    return t


# Clean data for category Pedagogische gesprekken
def ped_ges(t):
    t = t.split('\n')
    t = [line.strip() for line in t]
    st = ''
    for line in t:
        st += line[line.find(':')+1:]
    return st


clean_func = {'Dokter Patient': ped_ges, 'Psychologische gespreksvoering': ped_ges, 'Test': dok_pat, 'interviews': ped_ges}

if __name__ == "__main__":
    text = 'ik ik kan misschien nou nee kijk nee, maar, soort, soort soort klein klij ik i i door door sta, sta. st. se osp paosk i moeo sm eisis i isi s ss mij zijn mij zijn door'
    print(remove_stutters(text))
#     examples = [
#         "k zag t niet meer, das gek hè",
#         "'s ochtends drink ik koffie en 's avonds thee",
#         "zo'n 50% van de mensen, tis gewoon zo",
#         "mn tas ligt d'r naast, oke?",
#         "Tis nou ja, wat het is.",
#         "et cetera, etcetera",
#         "goeiedag! hoe gaat het mekaar?",
#     ]
#
#     print("=== Using base `rules` only ===")
#     for ex in examples:
#         print(f"IN : {ex}")
#         print(f"OUT: {apply_ruleset(ex, rules)}")
#         print()
#
#
#     t = "hallo ik ben. door de woorden. wow crazy aaa cool, nice. asdw aaawdw. asdwaf wad adwa awwww. maar dan. huh hoeze. crazy work haha. gekke handoek. maar dan niet echt."
#     s = "hallo ik door de woorden. wow aaa crazy, nice. asdw aaawdw. asdwaf wad adwa. awwww hoi. maar dan. huh hoezo no way haha. gekke lol nee handoek cool maar dan wel"
#     # p = "ik [unaudible] zeg"
#     # r = "ik doe als jij zeg"
#     # error = jiwer.process_words(p, r)
#     # print(error)
#     # # # print(error.alignments[0][0].ref_start_idx)
#     # print(error.alignments[0][0])
#     print(align_sentences(t, s))
#
#     t1 = """Dokter: Goeiemiddag, neemt u plaats, dan zullen we de uitslag van het onderzoek gaan bespreken.
# Client: Goeiemiddag dokter, ik ben erg benieuwd.
# Dokter: Ja zoals u weet hebben net een echo gemaakt en we konden daarop duidelijk zien dat u een blindedarmontsteking heeft, en dit veroorzaakt ook de buikpijn die u heeft.
# Client: Oh, dat klinkt niet goed. Wat houdt dat precies in?
# Dokter: Het is een ontsteking van een aanhangsel van de blindedarm, de appendix. Hoe het ontstaat is niet helemaal duidelijk, maar het ontstaat vaak plotseling.
# Client: Oke, ik snap wel wat u bedoelt denk ik.
# Dokter: U klinkt nog niet overtuigd, maakt u zich zorgen?
# Client: Wel een beetje om eerlijk te zijn, is het wel goed te genezen?
# Dokter: Ja het is eigenlijk zonder ernstige complicaties goed op te lossen. Maar we moeten het wel gaan behandelen.
# Client: Oke, dat stelt me gelukkig gerust. Wat kan er dan gedaan aan worden?
# Dokter: Nou eigenlijk zijn er twee opties. Optie 1 is een operatie waarbij het ontstoken deel verwijderd wordt, dit is de optie waarvoor het vaakst gekozen wordt. De andere optie is behandelen met antibiotica. Die wordt dan direct via een infuus in de aders toegediend. En we kunnen samen kijken wat voor u de beste optie is.
# Client: Dat lijkt me wel fijn ja.
# Dokter: Ja en na de operatie kan de ontsteking nooit terugkomen, omdat het ontstoken deel in z’n geheel verwijderd wordt. Het terugkomen van de ontsteking noemt men ook wel een recidief en de kans op een recidief na behandeling met antibiotica ligt tussen de 20 en 30% in de 2 jaar na de behandeling.
# Client: Maar zitten d'r niet ook nadelen aan een operatie?
# Dokter: Ja, een operatie kan gepaard gaan met complicaties, ook al zijn deze veelal klein. De operatie wordt onder narcose gedaan met een kijkoperatie.
# Client: Oke maar is het niet zo dat de darm misschien minder goed functioneert omdat je het weghaalt?
# Dokter: Nee, gelukkig niet. Dit stukje van de darm heeft geen functie, dus het weghalen heeft verder geen nadelen.
# Client: Ik ben ook nog wel benieuwd naar wat details over de behandeling met antibiotica.
# Dokter: Ja voor de behandeling met antibiotica moet u een paar dagen opgenomen worden om de antibiotica toe te dienen. De opname duurt korter dan de keuze als je kiest voor een operatie. Na een behandeling met antibiotica herstelt u wel sneller dan na de operatie. Maar een onderliggende oorzaak van de ontsteking kan niet achterhaald worden, bij een operatie kan dat wel.
# Client: Wat kunnen die oorzaken dan zijn?
# Dokter: Nou ja, de meest ernstige oorzaak is een vorm van kanker. Die komt niet vaak voor hoor, maar bij 1 of tot 2 procent van de mens.
# Client: Hmm, dat is niet veel, maar het lijkt me geen fijn idee om met die onzekerheid te leven.
# Dokter: Ja dat is begrijpelijk dat u dat zegt. Was het verder betreft de behandelopties wel duidelijk wat de voor- en nadelen zijn of heeft u nog vragen?
# Client: Nee, dat is eigenlijk wel duidelijk.
# Dokter: Heeft u op dit moment een voorkeur voor een van beide behandelingen?
# Client: Ja, voor een operatie, ondanks dat het herstel misschien langer duurt. Ik vind het wel fijn om zeker te weten dat het niet terugkomt of misschien wel veroorzaakt wordt door een vorm van kanker. Vindt u dat een logische keuze?
# Dokter: Ja hoor, ik zou de meeste mensen een operatie adviseren.
# Client: Oke, kan ik even mijn partner op de hoogte stellen voor we verder gaan? Hij maakt zich namelijk nog wel wat zorgen.
# Dokter: Ja natuurlijk mag dat, dan bespreken we zo verder de vervolgstappen.
# """
#     t1 = ped_ges(t1)
#     t2 = """Goedemiddag, neemt u plaats. Dan zullen we de uitslag van het onderzoek gaan bespreken. Goedemiddag, dokter, ik ben erg benieuwd. Ja, zoals u weet, hebben we net een echo gemaakt. We konden daarop duidelijk zien dat u een blinde darmontsteking heeft, en dit veroorzaakt ook de buikpijn die u heeft. Oh, dat klinkt niet goed. Wat houdt er precies in? Ja, er is een ontsteking van een aanhangsel van de blinde darm, de appendix. Hoe het ontstaat, is niet helemaal duidelijk, maar het ontstaat vaak plotseling. Oké, ik snap wel wat u bedoelt, denk ik. U klinkt nog niet overtuigd. Maakt u zich zorgen? Wel een beetje om eerlijk te zijn. Is het wel goed te genezen?Ja, het is eigenlijk zonder ernstige complicaties goed op te lossen. Maar we moeten het wel gaan behandelen. Oké, dat stelt me gelukkig gerust. Wat kan er dan gedaan aan worden? Nou, eigenlijk zijn er twee opties. Optie 1 is een operatie waarbij het ontstoken deel verwijderd wordt. Dit is de optie waar het meest voor gekozen wordt. De andere optie is behandelen met antibiotica. Die worden dan direct via een infuus in de aardels toegediend. En we kunnen samen kijken wat voor u de beste optie is. Dat lijkt me wel fijn, ja. Na de operatie kan de ontsteking nooit terugkomen omdat het ontstoken deel in zijn geheel verwijderd wordt. Het terugkomen van de ontsteking noemen we ook wel een recidief.De kans op recidief na behandeling met antibiotica ligt tussen de 20 en 30 procent in de twee jaar na de behandeling. Maar zitten er niet ook nadelen aan een operatie? Ja, een operatie kan gepaard gaan met complicaties, ook al zijn deze veelal klein. De operatie wordt onder narkoose gedaan met een kijkoperatie. Oké, maar is het dan niet zo dat de darm misschien minder goed functioneert omdat je het weghaalt? Nee, gelukkig niet. Dit stukje van de darm heeft geen functie, dus het weghalen heeft verder geen nadelen. Ik ben ook nog wel benieuwd naar wat details over de behandeling met antibiotica. Ja, voor de behandeling met antibiotica moet u een paar dagen opgenomen worden om de antibiotica toe te dienen.De opname duurt korter dan de keuze als je kiest voor een operatie. Na een behandeling met antibiotica herstelt u wel sneller dan na de operatie, maar een onderliggende oorzaak van de ontsteking kan niet achterhaald worden. Bij een operatie kan dat wel. Wat kunnen die oorzaken dan zijn? Nou ja, de meest ernstige oorzaak is een vorm van kanker. Die komt niet vaak voor, maar bij 1 of tot 2% van de mensen. Ja, dat is niet veel, maar het lijkt me geen fijn idee om met die onzekerheid te leven. Ja, dat is begrijpelijk dat u had zegt. Was het verder betreft op behandelopties wel duidelijk wat de voor- en nadelen zijn of heeft u nog vragen? Nee, dat is eigenlijk al duidelijk. Heeft u op dit moment een voorkeur voor een van beide behandelingen?Ja, voor een operatie. Ondanks dat het herstel misschien langer duurt. Ik vind het wel fijn om zeker te weten dat het niet terugkomt, of misschien wel veroorzaakt wordt door een vorm van kanker. Vindt u dat een logische keuze? Ja hoor, ik zou de meeste mensen een operatie adviseren. Oké, kan ik even mijn partner op de hoogte stellen voor we verder gaan? Hij maakt zich namelijk nog wel wat zorgen. Ja, natuurlijk mag dat. En dan bespreken we zo verder de vervolgstappen."""
#
#     ref, hyp = align_sentences(t1, t2)
#     for i in range(len(ref)):
#         print(ref[i], '\n', hyp[i], '\n\n')
#
#     # t = """Leger des heils, Christian health care organization,
#     # van uit  christelijke waarde helpen uhhh ummm duuh ahhhh zë mensën die dat zelf niet kunnen en/of nodig hebben
#     # most know for  providing shelter to the homeless
#     # many different    branches like child protective services"""
#     # h = 'uhh ahhh ammmm hallo sub'
#     # print(jiwer.process_words(t,h))
#     # print(normalize(t))
